{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default (printf "%s-%s" .Release.Name "sa") }}
  labels:
    app: {{ .Release.Name }}
{{- end }}
